backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

all-input-fields: &allFields
  - {label: Title, name: title, widget: string}
  - {label: Published, name: "published", widget: "boolean", default: false}
  - {label: Tags, name: tags, widget: "string", hint: "Comma seperated list of tags"}
  - label: "Featured Image"
    name: top_img
    widget: "image"
    default: "/images/blog/big_thumbnails/2019/2019-06-04-tacoma-city-5k/tacomacity5k.jpg"
    required: false
    media_library:
      config:
        multiple: false
  - label: "Race Details"
    name: race
    required: false
    widget: "object"
    fields: 
      - {label: "Location", name: "location", widget: "string", required: false}
      - label: Date
        name: date
        widget: "date"
        default: ""
        required: false
        format: "MM/DD/YYYY"
      - {label: "Distances", name: "distances", widget: "string", required: false}
      - {label: "Num Participants", name: "participants", widget: "string", required: false}
      - {label: "Pacing", name: "pacing", widget: "string", hint: "2:15", required: false}
      - {label: "Url", name: "participants", widget: "string", required: false}
      - {label: "Straava Url", name: "strava_url", widget: "string", required: false}
  - {label: Body, name: body, widget: markdown}

info: &allBlogInfo
  extension: .html.md.erb
  format: frontmatter
  create: true
  slug: '{{year}}-{{month}}-{{day}}-{{title}}'

collections:
  - name: blog2016
    label: "Blog 2016"
    folder: source/blog/2016
    <<: *allBlogInfo
    fields: 
      *allFields

  - name: blog2017
    label: "Blog 2017"
    folder: source/blog/2017
    <<: *allBlogInfo
    fields: 
      *allFields

  - name: blog2018
    label: "Blog 2018"
    folder: source/blog/2018
    <<: *allBlogInfo
    fields: 
      *allFields

  - name: blog2019
    label: "Blog 2019"
    folder: source/blog/2019
    <<: *allBlogInfo
    fields: 
      *allFields